### ISSUE TITLE
Date / Time Problem

### ISSUE THREAD

**Issue by SmartM-ui** [roleoroleo/yi-hack-Allwinner-v2#246]
Hi,
By leaving the timezone setting blank, the date in the event records have the correct date (real time 00.56 - Time reported: 00:56):

<img width="770" alt="Schermata 2021-09-03 alle 01 06 49" src="https://user-images.githubusercontent.com/63554131/131927209-f58e3c9a-106b-4607-9ca7-5845e44dd149.png">

but the local time is two hours behind (real time sep 03 01:02:23 - time reported: sep 02 23:02:23

<img width="452" alt="Schermata 2021-09-03 alle 01 02 31" src="https://user-images.githubusercontent.com/63554131/131927254-d942aefb-c8c3-4fb3-8ee4-56ab39a25c53.png">

and also in the motion_files (see the end date) it is two hours behind (Real Time: 03.09.2021 00:58:22 - Time Reported: 2021.09.02 22:57:12)

<img width="388" alt="Schermata 2021-09-03 alle 01 04 10" src="https://user-images.githubusercontent.com/63554131/131927276-5b71bf2c-5931-4ce2-b71e-609e9f6e9b35.png">

If I set the timezone with the Italian value, the date in the event log is two hours ahead.

How should I set the value for the timezone to have a synchronization of all dates / times? 

Thanks

**Comment by roleoroleo** [comment]
How do you set timezone in the yi app?

**Comment by SmartM-ui** [comment]
> How did you set timezone in the yi app?

Hi @roleoroleo 

timezone in YIhome: UTC +1:00

**Comment by roleoroleo** [comment]
Plase, try to set timezone = GMT in the app.
Check this post: https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/203#issuecomment-918762012

**Comment by SmartM-ui** [comment]
> Plase, try to set timezone = GMT in the app.
> Check this post: [#203 (comment)](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/203#issuecomment-918762012)

Perfect!
Set UTC +0 in the YIHome app and set the correct timezone to YI-HACK.
Now the time is correct everywhere

**Comment by roleoroleo** [comment]
The name should be "Coordinated universal time".

**Comment by SmartM-ui** [comment]
> The name should be "Coordinated universal time".

That's right, I set Coordinated universal time! 
Thanks

**Comment by Jon8RFC** [comment]
@roleoroleo Am I missing a step?  I'm getting confused because it's not working as expected...
Yi Home 1080p
IFUSY65U5W
9.0.36.02_202105081647
y211ga

Even if I disable NTPD, times don't seem to match up, universally.  There seem to be different variables.
For example, if the time is December 4, 2021 23:05:00 (GMT-6) and I've set the following and then rebooted:
Yi-Hack: CST6CDT,M3.2.0,M11.1.0
Yi-Hack NTPD: disabled
Yi app: Coordinated universal time

**I'm rounding off numbers and keeping them consistent after observing the changes, for simplicity in showing the issue...**
Bolded are changes.
I'm sorry for the wall of text, but I wanted you to see what changes.

My computer shows "December 4, 2021 23:05:00" (correct)
Yi-Hack web status shows "Sat Dec 4 23:05:00 CST 2021" (correct)
Recording folder being recorded to is "2021Y12M04D23H" (correct)
Filezilla client to Yi-Hack FTP recorded file (dynamically changes, not read/write) modified time shows "12/4/2021 17:05:00" (6 hours behind)

Now, if I remove the timezone set in Yi-Hack configuration page, save, power cycle completely (not a soft reboot):
My computer shows "December 4, 2021 23:05:00" (correct)
Yi-Hack web status shows "Sun Dec 5 05:05:00 GMT 2021" **(6 hours ahead)**
Recording folder being recorded to is "2021Y12M05D05H" **(6 hours ahead)**
Filezilla client to Yi-Hack FTP recorded file modified time shows "12/4/2021 23:05:00" **(correct)**

Now, if I change the Yi app timezone to UTC-06:00, power cycle, nothing seems to change.

Now, if I change the Yi-Hack timezone to CST6CDT,M3.2.0,M11.1.0, save, power cycle:
My computer shows "December 4, 2021 23:05:00" (correct)
Yi-Hack web status shows "Sat Dec 4 23:05:00 CST 2021" **(correct)**
Recording folder being recorded to is "2021Y12M04D23H" **(correct)**
Filezilla client to Yi-Hack FTP recorded file (dynamically changes) modified time shows "12/4/2021 17:05:00" **(6 hours behind)**

Now, if I "Disable Cloud", "Enable Recording without Cloud", "Enable NTPD", save, power cycle:
My computer shows "December 4, 2021 23:05:00" (correct)
Yi-Hack web status shows "Sat Dec 4 23:33:12 CST 2021" (correct)
Recording folder being recorded to is "2021Y12M04D23H" (correct)
Filezilla client to Yi-Hack FTP recorded file (dynamically changes) modified time shows "12/4/2021 18:05:00" **(5 hours behind)**

Now, if I change the Yi app timezone to Coordinated universal time, power cycle, nothing changes.

Now, if I re-enable "Cloud" (keeping NTPD enabled), save, power cycle:
My computer shows "December 4, 2021 23:05:00" (correct)
Yi-Hack web status shows "Sat Dec 4 23:33:12 CST 2021" (correct)
Recording folder being recorded to is "2021Y12M04D23H" (correct)
Filezilla client to Yi-Hack FTP recorded file (dynamically changes) modified time shows "12/4/2021 18:05:00" **(6 hours behind)**

**Comment by pwrsoft** [comment]
I have the same issue with invalid dates in recording folders, as well as in file names.

**Comment by canuckray** [comment]
@roleoroleo , I am also having issues with timestamp / time zone on my Yi 1080 Home.

BUT.... the issue only presents itself on the date/timestamp overlay that is overlaid on the rtsp stream. 

My setup is:

- Yi 1080 Home, QFUS

- Using Yi App:  Time zone set to UTC +0000
- Yi Hack web: set time zone to my correct time zone, disabled cloud, enabled NPT time sync, reboot. 

The result:

Yi Hack web reports the local time correctly - 10:14am (I am GMT-4, so GMT would be 2:14pm)
However, the timestamp overlay on the rtsp stream shows 8 hours ahead!  It's as if it has added 4 hours to GMT, rather than subtracted 4 hours. (it is showing 18:14, as shown below).

I have tried different combinations of Yi time zone, NTP on/off, Yi Hack time zone, and cannot get these to agree.

![image](https://user-images.githubusercontent.com/79683004/150367141-23b4427f-2fbe-471f-bcc8-ba8f2834a07a.png)

**Comment by roleoroleo** [comment]
Your problem is different because is related to the overlay.
And I don't know hot to solve it because it depends on the yi firmware.

But check if the "rmm" process has the correct environment variables.
Login with ssh.
Find the process id: `ps | grep rmm`
Check the environment: `cat /proc/<PID>/environ`

**Comment by canuckray** [comment]
Thanks for the quick reply - appreciate it.   The output is below.  Looks cryptic to me, but maybe something will jump out at you.

![image](https://user-images.githubusercontent.com/79683004/150382817-041e14ae-ed05-4426-afed-106f0ba42341.png)

**Comment by roleoroleo** [comment]
TZ variable is absent.
This is not ok.
What is yout timezone setting in the web interface?

**Comment by canuckray** [comment]
pasted from web interface:  EST5EDT,M3.2.0,M11.1.0

![image](https://user-images.githubusercontent.com/79683004/150420202-ed0bcaba-5b85-4e18-809e-82db5030a398.png)

**Comment by roleoroleo** [comment]
I checked the script and I can't understand.
Try another command:
`cat /proc/1172/environ | tr '\0' '\n'`

**Comment by canuckray** [comment]
![image](https://user-images.githubusercontent.com/79683004/150564302-07544566-b9a1-46aa-b2e5-30671c278855.png)

**Comment by SeriousPat** [comment]
di you fix it?
i habe UTC-0 in Yi app.
my timestamp up left in the video is incorret.

![image](https://user-images.githubusercontent.com/98743842/153624647-ad55fbff-c032-488b-aed5-be33cb49b542.png)

![image](https://user-images.githubusercontent.com/98743842/153624703-59f6b121-6f29-4ed5-90db-fcedcb0f4d09.png)

![image](https://user-images.githubusercontent.com/98743842/153624774-065e47cc-00ab-47bd-98f9-1d768f89c17e.png)

**Comment by roleoroleo** [comment]
I don't know how to fix it, at the moment.

**Comment by 1-Al** [comment]
FWIW I found using the setting GMT in the Yi app and TZ in Yi-Hack breaks the seek time in the Yi android app when trying to playback video. For those using RTSP and personal recorders I guess it doesn't matter but I ended up changing both yi app and yi hack to the proper timezone and only applying the timezone inline where needed in system.sh. For example with httpd, although others might be added. 

```
export TZ=$(get_config TIMEZONE)
if [[ $(get_config HTTPD) == "yes" ]] ; then
    mkdir -p /tmp/sd/record
    mkdir -p /tmp/sd/yi-hack/www/record
    mount --bind /tmp/sd/record /tmp/sd/yi-hack/www/record
    httpd -p $HTTPD_PORT -h $YI_HACK_PREFIX/www/ -c /tmp/httpd.conf
fi
# maybe some other apps here too
export -n TZ
```

But what works for me might not work for others and I don't know if Yi use daylight savings, maybe someone with daylight savings can shed some light? :) 

Example with above and +7hrs set for both Yi Hack (where needed) and the Yi app. The r30gb needs a workaround but the other camera's b091qp/h60ga seem fine.

 
![5](https://user-images.githubusercontent.com/94827997/154179180-e4e2c040-c28f-4993-b984-37f499c0c704.png)

**Comment by roleoroleo** [comment]
I wanted to try to do the opposite: run rmm without TZ.
But probably your solution is better.

**Comment by roleoroleo** [comment]
@SeriousPat 
Try this system.sh (overwrite the original one).
Set your timezone in the app (instead of UTC).
Reboot and check:

- Date/time in status web page.
- The watermark printed on the video and on the snapshot.
- If you are able to play videos captured with a motion (both web gui and app).

[system.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8095078/system.tar.gz)

**Comment by roleoroleo** [comment]
What about the date/time of the table in the "Events" page.
Is it ok? Or is it shifted by an offset?
I changed the system.sh and I reconfigured the correct time in the app.
Now, the time of the events is not ok.

**Comment by 1-Al** [comment]
Not sure who you are asking, if it's me then my event page is fine. Don't use MQTT, CRON and SSH seems to do it's own thing with time, as I said before I'm a noob with Linux and not that much better with Windows so don't know.

TBH just telnet/ssh and ftp would be enough for me with these camera's but it's nice to learn so I try a few things. Even learning a little arm and wrote a test grabber with piped aac and video streams from fshare. Audio was a bit hit and miss with my modification to rtsp_server_yi, the newer one you submitted works better than my attempt. Not sure what to do with videofile.cpp to get the 265 working, all those brackets and semi colons do my head in.  :/

**Comment by roleoroleo** [comment]
> Not sure what to do with videofile.cpp to get the 265 working, all those brackets and semi colons do my head in. :/

Check the last commit:
https://github.com/roleoroleo/RtspServer/tree/yi

**Comment by 1-Al** [comment]
Forgot to mention I'm not using ONVIF either and RTSP is being used for learning purposes, no dedicated box for it's use. Cloud is enabled but no cloud storage.

> Check the last commit: https://github.com/roleoroleo/RtspServer/tree/yi

Cool, will try it out later today. Will start another thread under discussions.

**Comment by kalyan02** [comment]
Thanks for the excellent software. Its magical to be able to ssh and play around into the camera.

Am facing similar date time problems.

I moved the `export TZ` to just before the `rmm` is executed, this seems to fix the folder label. However the overlay on top left is still 8 hours behind.

FYI: I am not using Yi App at all and all cloud features are disabled. Is there anyway to modify the firmware timezone offset? I am looking through #203 . Any tips?

**Comment by roleoroleo** [comment]
I don't know how to set the internal timezone (I mean the same that the app changes).

**Comment by rikrdo89** [comment]
I'm having the same issue. The timestamp on the rtsp feed is off by 5hrs, whenever I disable cloud. I have the yi app set to UTC. If I set the timezone to EST (which should subtract 5 hrs from UTC), it adds 5 hours more to the timestamp, so it shows a time that is 10hrs ahead. I tried multiple combinations of turning off ntdp, timezones, reboot cycles, but the timestamp seems to be always off unless I don't disable cloud.

**Comment by roleoroleo** [comment]
Is your TZ positive or negative?

**Comment by rikrdo89** [comment]
It's supposed to be negative... my TZ is EST5 (Eastern time, which UTC - 5 hr)

**Comment by roleoroleo** [comment]
Try to overwrite 2 files contained inside this archive:
[patch.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10093421/patch.tar.gz)

/tmp/sd/yi-hack/bin/set_tz_offset
/tmp/sd/yi-hack/script/system.sh

**Comment by rikrdo89** [comment]
Thanks a lot, I'll try that. Do I just ssh into the cam and overwrite those files, and reboot?, or Do I turn off the cam, take the micro sd and change the files in my computer, and then power on the cam?

**Comment by roleoroleo** [comment]
As you prefer.
Normally I use ftp. No need to change permissions because the file system is a fat32.
A reboot is required.

**Comment by canuckray** [comment]
I can confirm that these 2 files corrects the issue!   Beautiful!

Thanks @roleoroleo .... greatly appreciated!

**Comment by rikrdo89** [comment]
the patch works!!! Thanks a lot @roleoroleo, no more incorrect timestamp!

**Comment by itkfilelor** [comment]
Sadly, the system.sh file crashes both of my cameras on the current F/W (0.2.5)  (model: y211ga)

**Comment by roleoroleo** [comment]
Pay attention when you copy the file to the cam.
The file must be in linux format (LF line termination).

**Comment by itkfilelor** [comment]
> Pay attention when you copy the file to the cam.
> The file must be in linux format (LF line termination).

That should be easy since my daily is PopOs 😊
When it failed I also opened it up in VSCode to see what's up and I saw all \n no \r

**Comment by roleoroleo** [comment]
Please, check this commit:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/4db939ee69d7b134313dd2610be2b71cc328bf32

**Comment by itkfilelor** [comment]
> Please, check this commit: [4db939e](https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/4db939ee69d7b134313dd2610be2b71cc328bf32)

Just applied, if it fails, I only have 1 more shot til much later. At work right now. 😊
Technology is great.

**Comment by chrbar11** [comment]
> FWIW I found using the setting GMT in the Yi app and TZ in Yi-Hack breaks the seek time in the Yi android app when trying to playback video. For those using RTSP and personal recorders I guess it doesn't matter but I ended up changing both yi app and yi hack to the proper timezone and only applying the timezone inline where needed in system.sh. For example with httpd, although others might be added.
> 

Hi ghost, did you obtain the result when Cloud was disable?
I met trouble to set the good timezone for the built-in YI timestamp at left top ([#606](https://github.com/roleoroleo/yi-hack-Allwinner-v2/discussions/606#discussion-5003820)).

**Comment by chuckheron** [comment]
Hi,
I applied the patch, but as soon as I set TIMEZONE to anything, the camera wouldn't boot.

I was trying the TZP_SET calculation in /bin/sh, and I kept getting a 'bad substitution' with the  ${TZP:0:1} syntax.

I got it to work using sed:
`TZP_SET=$(echo $TZP | sed 's/\(.\)/\1 /g' | awk '{ print ($1($2$3)*3600+($4$5)*60) }')
`

My camera boots now and the times seem to be correct.

Sadly, it's not doing motion detection anymore though, but that's probably a different issue.

Thanks
-chuck

**Comment by roleoroleo** [comment]
> I was trying the TZP_SET calculation in /bin/sh, and I kept getting a 'bad substitution' with the ${TZP:0:1} syntax.

This is strange.
What happens if you run the followin commands?
```
root@yi-hack:~# export TIMEZONE=CET-1CEST,M3.5.0,M10.5.0/3
root@yi-hack:~# export TZP=$(TZ=$TIMEZONE date +%z)
root@yi-hack:~# export TZP_SET=$(echo ${TZP:0:1} ${TZP:1:2} ${TZP:3:2} | awk '{ print ($1$2*3600+$3*60) }')
root@yi-hack:~# echo $TZP_SET
```

**Comment by chuckheron** [comment]
Hi,

/bin/sh
sh$ export TIMEZONE=CET-1CEST,M3.5.0,M10.5.0/3
sh$ export TZP=$(TZ=$TIMEZONE date +%z)
sh$ export TZP_SET=$(echo ${TZP:0:1} ${TZP:1:2} ${TZP:3:2} | awk '{ print ($1$2*3600+$3*60) }')
sh: 3: Bad substitution
sh$ echo $TZP_SET

sh$

That syntax seems to work in bash, not sh though.

/bin/bash
bash$ export TIMEZONE=CET-1CEST,M3.5.0,M10.5.0/3
bash$ export TZP=$(TZ=$TIMEZONE date +%z)
bash$ export TZP_SET=$(echo ${TZP:0:1} ${TZP:1:2} ${TZP:3:2} | awk '{ print (
$1$2*3600+$3*60) }')
bash$ echo $TZP_SET
+7200
bash$

Thanks
-chuck






On Thursday, June 22, 2023 at 10:46:01 PM PDT, roleo ***@***.***> wrote: 







>  
> I was trying the TZP_SET calculation in /bin/sh, and I kept getting a 'bad substitution' with the ${TZP:0:1} syntax.
> 

This is strange.
What happens if you run the followin commands?
***@***.***:~# export TIMEZONE=CET-1CEST,M3.5.0,M10.5.0/3
***@***.***:~# export TZP=$(TZ=$TIMEZONE date +%z)
***@***.***:~# export TZP_SET=$(echo ${TZP:0:1} ${TZP:1:2} ${TZP:3:2} | awk '{ print ($1$2*3600+$3*60) }')
***@***.***:~# echo $TZP_SET

**Comment by roleoroleo** [comment]
Sorry bu I don't understand, inside the cam sh and bash are symbolic links to ash.
Where are you running, these commands?

**Comment by chuckheron** [comment]
Hi
Yes, sorry, I was running them on a linux machine, I tried it on the camera there is no error.  
Now I'm not sure why the camera wasn't booting with that code in there.
It's working now..

Thanks
-chuck

**Comment by sirduke989** [comment]
> Try to overwrite 2 files contained inside this archive: [patch.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10093421/patch.tar.gz)
> 
> /tmp/sd/yi-hack/bin/set_tz_offset
> /tmp/sd/yi-hack/script/system.sh

I can confirm that the set_tz_offset in this patch fixes the OSD timestamp for a negative tz offset (CST/CDT) but does not appear to be included in the latest version (0.2.9). I tested this on RFUS both Indoor (y211ga) and Outdoor (h30ga) cameras running version 0.2.9. Note: I did not need to replace system.sh.

To get this to work:

1. I re-enabled cloud integration and rebooted
2. I set to timezone to Coordinated universal time in the Yi-Home app
3. I disabled cloud integration, set the correct timezone and enabled time OSD in Yi-Hack
4. Rebooted (Offset was still doubled, IE +10 instead of -5)
5. I replaced set_tz_offset from the patch on the camera
6. Rebooted (now the OSD timestamp is displaying correctly)

**Comment by roleoroleo** [comment]
This is weird.
I included the fixes in the master branch and tested again in this moment.
It works with my h52ga (0.2.9) using "CST6CDT,M3.2.0,M11.1.0".

Please run the commands in this post, using your timezone and check the output.

**Comment by sirduke989** [comment]
@roleoroleo I actually did try those commands prior to replacing set_tz_offset on 0.2.7 and 0.2.9 and it always gave the correct offset for me of -18000. This lead me to think that the issue was with set_tz_offset and not system.sh. I should have included this in my last post but I am also using "CST6CDT,M3.2.0,M11.1.0" as my Timezone in the UI.

Here are the commands ran on one of my cameras:
root@yicamout:~# export TIMEZONE=CST6CDT,M3.2.0,M11.1.0
root@yicamout:~# export TZP=$(TZ=$TIMEZONE date +%z)
root@yicamout:~# export TZP_SET=$(echo ${TZP:0:1} ${TZP:1:2} ${TZP:3:2} | awk '{ print ($1$2*3600+$3*60) }')
root@yicamout:~# echo $TZP_SET
-18000

I did some more testing and tried replacing set_tz_offset from different patches on one of my RFUS cameras running y211ga 0.2.9 and below are the resulting OSD:
From patch.tar.gz: OSD is UTC-5 (correct)
y211ga (0.2.9): OSD is UTC+5
h52ga (0.2.9): OSD is UTC+5
y211ga (0.2.7): OSD is UTC+5
y211ga (0.2.6): OSD is UTC-5 (correct)
y211ga (0.2.5): OSD is UTC-5 (correct)
y211ga (0.2.4): OSD is UTC-5 (correct)

**Comment by roleoroleo** [comment]
Ok, the last try:
set_tz_offset writes 4 bytes to the file /tmp/mmap.info
You can check if it writes properly reading the file:
`hexdump -C -s 0x04e0 -n 4 /tmp/mmap.info`

The offset depends on the model and it's in the following table:
```
    { 0x4a0, 1 },    // Y20GA_9
    { 0x4a4, 1 },    // Y20GA_12
    { 0x4a0, 1 },    // Y25GA
    { 0x4a0, 1 },    // Y30QA

    { 0x4e0, 1 },    // H30GA_9
    { 0x56c, 0 },    // H30GA_11     Already present
    { 0x4e0, 1 },    // H51GA
    { 0x4e0, 1 },    // H52GA
    { 0x560, 0 },    // H60GA        Already present
    { 0x4e0, 1 },    // Q321BR_LSX
    { 0x4e0, 1 },    // QG311R
    { 0x4e0, 1 },    // R30GB
    { 0x56c, 0 },    // R35GB        Already present
    { 0x560, 0 },    // R40GA        Already present
    { 0x4e0, 1 },    // Y211GA_9
    { 0x570, 0 },    // Y211GA_12    Already present
    { 0x4e0, 1 },    // Y21GA_9
    { 0x564, 0 },    // Y21GA_12     Already present
    { 0x4e0, 1 },    // Y28GA
    { 0x56c, 0 },    // Y291GA_9     Already present
    { 0x570, 0 },    // Y291GA_12    Already present
    { 0x4e0, 1 },    // Y29GA
    { 0x000, 0 }     // B091QP       0x560 or 0x56c but already present
```

Try to run set_tz_offset and check if the number is ok.
For example:
```
root@yi-hack-h52ga:~# set_tz_offset -c tz_offset_osd -m h52ga -f 9 -v -18000
root@yi-hack-h52ga:~# hexdump -C -s 0x04e0 -n 4 /tmp/mmap.info
000004e0  b0 b9 ff ff                                       |....|
000004e4
```

**Comment by sirduke989** [comment]
I should also mention that I am running v12 of the firmware and each test below was performed after a fresh reboot of the camera. I also ran the hexdumps (for both v9 and 12 addresses) before and after the set_tz_offset command.

Booted with set_tz_offset from y211ga_0.2.9:
```
root@YICAM1:~/bin# hexdump -C -s 0x570 -n 4 /tmp/mmap.info
00000570  50 46 00 00                                       |PF..|
00000574
root@YICAM1:~/bin# hexdump -C -s 0x4e0 -n 4 /tmp/mmap.info
*
000004e0
root@YICAM1:~/bin# set_tz_offset -c tz_offset_osd -m y211ga -f 9 -v -18000 -d
debug on
The size of the buffer is 3756
Mapping file /tmp/mmap.info, size 3756, to b6f8d000
Closing the file /tmp/mmap.info
Unmapping file /tmp/mmap.info, size 3756, from b6f8d000
root@YICAM1:~/bin# hexdump -C -s 0x570 -n 4 /tmp/mmap.info
00000570  50 46 00 00                                       |PF..|
00000574
root@YICAM1:~/bin# hexdump -C -s 0x4e0 -n 4 /tmp/mmap.info
000004e0  b0 b9 ff ff                                       |....|
000004e4
```

Since I am on version 12 of the firmware I also tried changing that in the command line (looks like it doesn't work when passing in version 12):
```
root@YICAM1:~# hexdump -C -s 0x570 -n 4 /tmp/mmap.info
00000570  50 46 00 00                                       |PF..|
00000574
root@YICAM1:~# hexdump -C -s 0x4e0 -n 4 /tmp/mmap.info
*
000004e0
root@YICAM1:~# set_tz_offset -c tz_offset_osd -m y211ga -f 12 -v -18000 -d
debug on
root@YICAM1:~# hexdump -C -s 0x570 -n 4 /tmp/mmap.info
00000570  50 46 00 00                                       |PF..|
00000574
root@YICAM1:~# hexdump -C -s 0x4e0 -n 4 /tmp/mmap.info
*
000004e0
```

Not sure if this will help but with set_tz_offset from patch.tar.gz (when OSD is showing correctly):
```
root@YICAM1:~# hexdump -C -s 0x570 -n 4 /tmp/mmap.info
00000570  b0 b9 ff ff                                       |....|
00000574
root@YICAM1:~# hexdump -C -s 0x4e0 -n 4 /tmp/mmap.info
*
000004e0
root@YICAM1:~# set_tz_offset -c tz_offset_osd -m y211ga -f 12 -v -18000 -d
set_tz_offset: unrecognized option: c
set_tz_offset: unrecognized option: m
set_tz_offset: unrecognized option: f
debug on
Setting timezone to -18000000 ms
root@YICAM1:~# hexdump -C -s 0x570 -n 4 /tmp/mmap.info
00000570  b0 b9 ff ff                                       |....|
00000574
root@YICAM1:~# hexdump -C -s 0x4e0 -n 4 /tmp/mmap.info
*
000004e0
```

Also thank you for all your hard work on helping make this project possible!

**Comment by roleoroleo** [comment]
The problem is probably related to the "-f" parameter.
You should usd "-f 12" but it doesn't work.
I will check it.

**Comment by roleoroleo** [comment]
I think I found the problem.
Based on the dumps I received from other users, I thought it was already set for this model.
So the code skips the write operation.
I will remove this limit.

**Comment by roleoroleo** [comment]
Please, try this:

[set_tz_offset.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/12122094/set_tz_offset.gz)

**Comment by sirduke989** [comment]
Looks good, thank you.

After replacing set_tz_offset with the one in the previous post and rebooting the camera, I now see the correct OSD and the hexdump looks good.

```
root@YICAM1:~# hexdump -C -s 0x570 -n 4 /tmp/mmap.info
00000570  b0 b9 ff ff                                       |....|
00000574
```

**Comment by sirduke989** [comment]
Also tested on Yi Camera Outdoor RFUS on firmware version 12 running 0.2.9 for h30ga and it looks good.

**Comment by hiagocosta** [comment]
> Please, try this:
> 
> [set_tz_offset.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/12122094/set_tz_offset.gz)

i'm experiencing the same error, can I use this on my y291ga with 9.3.5 fw?
im on the latest update since now (0.2.9)...

just overwrite the bin file?

**Comment by roleoroleo** [comment]
Yes, you can try it.
Rename the old binary and copy the new one.

**Comment by hiagocosta** [comment]
Thanks, it worked like a charm!

Em seg., 23 de out. de 2023 às 09:01, roleo ***@***.***>
escreveu:

**Comment by hiagocosta** [comment]
updating this issue,
it does not corrected, I think that after a period of time the cam lost de access of ntp and returning back to UTC without TZ

**Comment by kiddyfurby** [comment]
I saw the 0.3.1 changelog and was very excited because the long standing issue of OSD timezone is corrected!

We're getting there! but for 1 of my 3 y29ga, the timezone is incorrect.
On the one y29ga, `set_tz_offset -c tz_offset_osd -m y29ga -f 9 -v 0 -d` did correct the OSD time

The two y29ga without timezone issue had Base Version 9.0.09.06_202103291039
The one which required manual set_tz_offset has 9.0.09.**03_202006090939**

I do not have yi app so that settings is whatever value the default is.

**Comment by karlitos** [comment]
Hello, after reading this while thread I am still quite confused what to do to get the timezone settings right. My camera is:
My camera is the Yi Dome U Pro 2K:

+ Firmware Version | 0.3.3
+ Base Version | 9.0.27.14_202103082324
+ Model Suffix | h60ga

I do not have the Yi app, never used it and never set anything via the app. I set the timezone via the WebUI. The local time shown in the WebUI is right, the time shown in the camera overlay is also right, but the the system time seems to be wrong is two hours behind but in the Events view in the WebUI the the time is two hours ahead.

What can I do to fix it permanently ?

**Comment by roleoroleo** [comment]
This page is very old and refers to an outdated version of the hack.

What's your timezone string?

> The local time shown in the WebUI is right

Ok.

> the time shown in the camera overlay is also right

Ok.

> the the system time seems to be wrong is two hours behind

If you mean the time in a terminal session, this os ok.

> but in the Events view in the WebUI the the time is two hours ahead.

This is not ok, please send me a full screenshot of the Events page.

**Comment by karlitos** [comment]
Thanks for the reply, upon further investigation I found the `Select the time used by your cam to save the events` control in the events view. It was set to __Auto__ and after manually setting it to __Local time__ the recordings are displayed under right timestamp.
