### ISSUE TITLE
How to reset if hw button is broken 

### ISSUE THREAD

**Issue by Mrivilla** [roleoroleo/yi-hack-Allwinner-v2#317]
Hi,
I have a new YI Dome U. Hack is working perfectly, but reset button doesn’t work. It seems is not present or broken. I’m not eagle enouth to dismantle the camera.
Is there any possibility to force factory hard reset executing a boot command or though ssh access?
Thanks.
Marcos

**Comment by roleoroleo** [comment]
Why do you need to do a reset?
What type of reset do you mean?
Reset of the yi config or hack config?

**Comment by Mrivilla** [comment]
I have the camera with the hack and works, but unfortunately I need to enroll again the camera to the mobile application. To do that, it would be necessary press the reset button, but the button is broken or doesn't exit, so I cannot initiate the process to enroll the camera to the mobile app.  Just wondering what are the files that the hard reset to initiate the enrollment process again.
Then after the added to the mobile can add the hack again. The backup that I've taken  just was after the first enrollment before the hack, so I'm still have the same problem.
Maybe a factory backup restoration it would be enough.

**Comment by roleoroleo** [comment]
To reconnect the cam to the app, simply switch off "Disable Cloud".

**Comment by Mrivilla** [comment]
Thanks

**Comment by LarryMassey** [comment]
Just took my camera apart & the reset button was laying inside the unit… I needed to reset because TMobile replaced my modem & 9 cameras later… this one wouldn’t reset pics included… So I Won’t Be Able to Use this on…
![A7938128-3FE5-47A9-89D7-FB676AFB048A](https://user-images.githubusercontent.com/122818445/212734822-2cae6c8f-ad00-46b2-a4f3-b4ba2bc7700a.jpeg)
![DE1D948A-38BA-4451-8567-CE0143A31E2E](https://user-images.githubusercontent.com/122818445/212734833-691e77d5-a020-4fc4-92c4-908813a24957.jpeg)
