### ISSUE TITLE
Time in events

### ISSUE THREAD

**Issue by JozefLu** [roleoroleo/yi-hack-Allwinner-v2#622]
Hi,
yi-hack-Allwinner-v2 on my Yi Home Camera:
Firmware Version	0.2.6
Base Version	12.0.35.8_202211241029
Model Suffix	y291ga
Serial Number	RFUSY62xxxxxx
Motion detection is ON.
Time Zone in hack is: CET-1CEST,M3.5.0,M10.5.0/3
and is the same in app
But the time in Events is shifted 2h and I think is GMT, not mine.

**Comment by roleoroleo** [comment]
What do you mean with "But the time in Events is shifted 2h and I think is GMT, not mine."?
Where do you see GMT?

**Comment by JozefLu** [comment]
O, sorry, I did not expleined it clearily.
Below is an example - the time is 10:00:
![image](https://user-images.githubusercontent.com/70907241/236622782-921a32a5-8d62-4c5d-abb4-819c72c26752.png)


Inside is the same time 10:xx:
![image](https://user-images.githubusercontent.com/70907241/236622760-849fda15-b94b-45b5-b3df-8b6828bbf0de.png)

But in the reality is 12:xx (the right time is only shown as a timestamp in the recording file):
![image](https://user-images.githubusercontent.com/70907241/236623027-1abfbbfa-cd9e-4fe8-8484-44f8e7e24dfe.png)

**Comment by roleoroleo** [comment]
Please, try to apply this patch:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/8bb5c60e0c18a4bcca1d61d00b703b368b455c43

**Comment by thecount2a** [comment]
I think the problem here is with devices with built-in device OSDs don't get a TZ offset set at all.  Since I have the t211ga firmware, my OSD is also wrong unless I add this line to startup.sh:

set_tz_offset -c tz_offset -v -14400

The system.sh script runs this command but it does nothing for my built-in OSD:

set_tz_offset -c tz_offset_osd -m y211ga -f 12 -v -14400

As a workaround @JozefLu you can add a similar line for your timezone offset to a file in your root directory called "startup.sh"

@roleoroleo I think this bug has something to do with negative timezone offsets not working correctly (maybe the negative sign is being dropped) because I can set positive timezone offsets just fine but it treats negative offsets as positive offsets.  For my -4 hour timezone offset, it adds 4 hours instead of subtracting 4 hours.  EST-4 gives me the same OSD value as EST4, but the system time is different for those two settings.  I can set my timezone to EST20 and get the correct time but then the date value is 1 day ahead!

**Comment by michal0125** [comment]
I have the same issue. 

Firmware Version | 0.2.9
Base Version | 12.0.37.0_202211241030
Model Suffix | y211ga
Serial Number | IFUSY65xxxxxxxxxxx

**Comment by roleoroleo** [comment]
Please, recap the problem.
I have released a couple of versions since this issue was opened.

**Comment by pafade89** [comment]
Hi @roleoroleo,

I have the same issue with my IFUS Home Cam. The Local Time on the landing page and the watermark time in the video are correct. The event time on the event page is 2 hours too early.

Same like @JozefLu 

Cheers P

**Comment by roleoroleo** [comment]
Do you mean the 1st column of the page "Date & Time"?

Please, give me some details:
- suffix
- fw version
- hack version
- time zone configured

**Comment by pafade89** [comment]
Hi,

Timezone is:

> CET-1CEST,M3.5.0,M10.5.0/3

Here are the Cam Infos

![Screenshot_20230924_184314_Chrome.jpg](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/113902279/c74b5ba1-3cc9-4d99-8935-2403b36c93ed)

And here the problem:

![Screenshot_20230924_184146_Chrome.jpg](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/113902279/a11f300a-50b8-4dbd-9de7-416c8fda7815)

The Event URL is also wrong:

http://IP:Port/?page=eventsfile&dirname=2023Y09M24D16H

**Comment by roleoroleo** [comment]
What's the time configuration in the app?

**Comment by pafade89** [comment]
![Screenshot_20230926_112957_Kami Home.jpg](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/113902279/c9f9053c-713a-4a57-aa9c-c958cab091bf)

**Comment by roleoroleo** [comment]
Sorry, I need time to fix this issue.

**Comment by pafade89** [comment]
Unstale

**Comment by roleoroleo** [comment]
I'm not able to autodetect the correct time for all models.
So I added a configuration option.
Please, try this beta:
[h30ga_0.3.0.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13841245/h30ga_0.3.0.tar.gz)

**Comment by roleoroleo** [comment]
yi-hakc/www and yi-hack/script folders are enough.

And a reboot before to configure it.

**Comment by pafade89** [comment]
After switching to 'local time' in the drop-down menu, saving, and rebooting, the menu reverts to 'auto detect'.

It also has no effect on the timestamp.

**Comment by roleoroleo** [comment]
> I tried it today, set it to GMT, but the folder name still doesn't match, so the link isn't right (see screenshot).

This is normal.
The name of the folder is GMT.
But the column "Date & Time" must be ok, aligned with the local time.

**Comment by roleoroleo** [comment]
The time you see in the app should be the same as the time in the "Date & Time" column (or "Time" column in the 2nd web page).
The "Directory name" column, however, is different: it's in GMT time because the folder is created by a Yi process that works in GMT.
So, there is a translation between the folder and the event time.

If you are in UTC+1 timezone, in this moment you should see a 1 hour offset between them (for your cam model).
In this post https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/622#issuecomment-1881440682 the behavoir seems correct.
In this post it's not ok https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/622#issuecomment-1883129202.

For your specific model you should set "GMT". The meaning of the switch is: "what time your cam is using to save video files?"
If the folders in /tmp/sd/records are saved with GMT time, set "GMT".
If the folders in /tmp/sd/records are saved with local time, set "local time".

**Comment by pafade89** [comment]
@roleoroleo 
Thank you for your explanation. However, the question that now arises for me is why my other three Yi Outdoor Cameras display everything perfectly. Two of them have the Yi Hack 5, and the other two have the Yi Hack Allwinner v2 from you, out of my total of 4 cameras.

Yi Hack Allwinner v2:

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/113902279/2aa1bfff-f2e7-4c5f-a2bc-5439dee2d73e)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/113902279/7b6e6de5-d6f1-454e-bc67-ce8ca3339ea8)

Yi Hack v5:

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/113902279/a474ee79-cbd1-4cff-becc-c68a0d079bbe)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/113902279/467fa137-6164-4c57-930c-5688ebc4dd72)

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/113902279/260fd319-7ebd-43ad-9189-f2f79f75e98e)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/113902279/15e38aef-2b59-4f1d-b9c5-8145fd1d95ce)

I hope that helps, maybe.

**Comment by pafade89** [comment]
I thank you for the implementation, and I assume we can close the issue, right?

**Comment by roleoroleo** [comment]
In the next release, I completely changed this behavior.
But we will open a new issue, if necessary.

**Comment by pafade89** [comment]
That sounds great =) I'll wait for further updates.

#close this issue
