### ISSUE TITLE
Support Request: Yi/Xiaoyi Camera Y4

### ISSUE THREAD

**Issue by cmeng-gao** [roleoroleo/yi-hack-Allwinner-v2#712]
I have a Yi/Xiaoyi Camera Y4 in my hand

Version: 9.0.09.06, 202103291039

ID: IFCNY39YFQ**********

What should I do?

**Comment by roleoroleo** [comment]
Use y29ga

**Comment by roleoroleo** [comment]
Did you fix the problem with yellow light?

**Comment by boer0327** [comment]
In my case, I saw Factory.done folder too. but the camera will keep restarting. when I try to remove the SD card, it will go to normal without hack.

my version is 9.0.58.00_202206211052

Could you help me with this? thx

**Comment by boer0327** [comment]
[log_no_wifi_dev.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/12999752/log_no_wifi_dev.tar.gz)
 btw this is my log file, is it caused by no wifi issue? but I think it should not auto restart even if there is no wifi connected.  but actually, I have configured Yi app and wifi working fine.

**Comment by roleoroleo** [comment]
> my version is 9.0.58.00_202206211052

Sorry but your cam is not supported at the moment.
Please send me a backup of the original firmware.

**Comment by boer0327** [comment]
thx roleoroleo. please refer to the original firmware below. any update, please let me know, thx. 

[backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13039456/backup.zip)

**Comment by roleoroleo** [comment]
Please try this beta:
[y213ga_0.2.9.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13039915/y213ga_0.2.9.tar.gz)

If RTSP and snapshot don't work, send me a copy of the file /dev/shm/fshare_frame_buf

**Comment by roleoroleo** [comment]
Your cam uses hevc.
I need time to add the support.

**Comment by boer0327** [comment]
ok, thx. let me know if you have further update for this. is there anyway I can downgrade camera to old version?

**Comment by roleoroleo** [comment]
Old fw version?
Or old hack version?

Try these new binaries:
[bins.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13057571/bins.tar.gz)

**Comment by roleoroleo** [comment]
Old fw version or old hack version?

Try these binaries:
[bins.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13057612/bins.tar.gz)

**Comment by boer0327** [comment]
Thx reoleoroleo. I mean old fw version. I was thinking you may not be that quick to finish the new version. so I am trying to downgrade to old fw version and it may can temp to solve this issue. But you are amazing. very quick to get this update. thank you so much. I will try it later today. and will let you know, if there still has any issue.

**Comment by boer0327** [comment]
Thx reoleoroleo. good news, High res stream is working. 
Low res snapshot work as well. 
But High res snapshot still not working. this is main feature what I wanted. because I am using MJPEG-Streamer connect. please help. thx

**Comment by roleoroleo** [comment]
> Thx reoleoroleo. I mean old fw version. I was thinking you may not be that quick to finish the new version. so I am trying to downgrade to old fw version and it may can temp to solve this issue. But you are amazing. very quick to get this update. thank you so much. I will try it later today. and will let you know, if there still has any issue.

It's possible to downgrade to another fw version (if you have it) but this will not help to run this hack.
This model (y213ga) is new and it's not supported.

> But High res snapshot still not working. this is main feature what I wanted. because I am using MJPEG-Streamer connect. please help. thx

I will check the code.

**Comment by boer0327** [comment]
ahh, that makes sense. I saw this model support H265, in yi app, I can switch mode between h264/h265.

thank you so much, let me know if any updates. :)

**Comment by roleoroleo** [comment]
Ok, try these binaries:
[bins.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13063938/bins.tar.gz)

**Comment by boer0327** [comment]
thx roleoroleo. everything is working now.
but there are still has big problem, video update very slow. it is about 30s delay for every move. this is almost cannot use on any place. :( . But when I try use yi APP. everything is sync without any problem. I think there are still has something wrong. please have look. Let me know if you need any log or something. thx so much for you update. I think almost there.

**Comment by boer0327** [comment]
<img width="894" alt="image" src="https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/1627892/5ecde953-57a5-48e7-82f4-396438da56cf">
here is top command given result. CPU looks much higher, but Yi App video looks ok. so I am not sure what happen. just give you for refer.

**Comment by roleoroleo** [comment]
I don't understand.
Is video low in terms of fps?
Is there too much delay?

**Comment by boer0327** [comment]
yes, it is too much delay. for example, if you wave your handle in the camera, normally it will wave your handle just in time in the app/stream. actually, Yi app is just in time. I am using the RTSP stream play on VLC, it will be delayed about 15s. If I am using MJPG stream and check it on the website. it will delay about 30s.  Is this clear for this issue?

**Comment by roleoroleo** [comment]
> yes, it is too much delay. for example, if you wave your handle in the camera, normally it will wave your handle just in time in the app/stream. actually, Yi app is just in time. I am using the RTSP stream play on VLC, it will be delayed about 15s.

Please, try another client, for example WebRTC, if you have Home Assistant.

> If I am using MJPG stream and check it on the website. it will delay about 30s. Is this clear for this issue?

MJPEG?!? The cam doesn't stream with MJPEG, only h264/hevc. What do you mean exactly?

**Comment by boer0327** [comment]
<img width="829" alt="image" src="https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/1627892/722957b8-7184-4dc9-bf18-fe39c03fafbe">
sorry for confusing you.
see what I have attached doc. why I cannot use WebRTC, because it is because only support Raspberry device. So I have to use Adaptive MJPEG-Streamer. this uses a snapshot URL and pulls individual images. see the above screenshot.

so in the hacker page, it has high res snapshot (http://192.168.0.46/cgi-bin/snapshot.sh?res=high&watermark=yes). I use it add to system. it looks working, but 

so I use this high res snapshot to add it in system. it's looks working. but the problem is the picture lag is very serious. 
I am try to figure out it is cause by system issue or snapshot issue.  I am trying to open the snapshot url on chrome. refresh page about 2 sec. I saw this page also dealy. so I think it is cause by snapshot page issue. 

I hope this is make sense for you. the key problem should be snapshot slow and dealy.

**Comment by boer0327** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/1627892/cf8e6e73-8754-4c33-af01-a70a74e1dbd8

let me give you an example, you can see the above video, the left one is using high res snapshot(Adaptive MJPEG-Streamer). and the right side is RTSP stream play on VLC. you can see how delay for the left screen. almost not working.

**Comment by boer0327** [comment]
and I am sure this is not cause by mainsail(it is printer manage sysytem which you see left UI) issue. because I have use another camera using same way, everything is working correctly. 
RTSP looks ok, but it is still dealy than Yi app output. 

I think snapshot issue should be cause by imggrabber in bin folder? I am not familiar with this. just some guess. :)

Let me know if you get any feedback, thx

**Comment by roleoroleo** [comment]
Sorry but you can't fix this problem.
Snapshot feature is very expensive in terms of cpu/memory resources and the process to take a snapshot requires a lot of time.
So, if you create a stream with a snapshot sequence, it will be delayed.
You have to use the rtsp protocol, with the rtsp url or through the onvif protocol.

**Comment by boer0327** [comment]
ok, got it. thx. but seems rtsp protocol looks still delay than Yi APP and some time it will frezon, you can check the above video. but YI app will don't have this problem. could you optimize it. or if you can build a H265 version? I think it will much fast than H264.

**Comment by roleoroleo** [comment]
Yi app uses a custom protocol to deliver the stream.
The delay of the rtsp protocol is higher than the delay of the app but it's not so big.
And it depends on the client, for example if you use WebRTC component in ha, the delay is very low.
About h265 I can't change the codec because the stream is produced by the hw accelerator inside the soc.
There is an experimental setting https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/484#issuecomment-1251916480 that changes codec from h264 to h265 and viceversa but it's tested only for r30gb.

**Comment by boer0327** [comment]
thx roleoroleo for explain this. that's all make sense. 

I think I find delay issue. if I am try to disable movement event feature on YI app, everything will much fast than before. and all dealy is acceptable. 

I try to bypass snapshot feature. I am use a docker container to convert rstp to jpg on my router(because my router is much powerful device). use this way snapshot dealy also been fixed. 

so I think your solution basic working for this camera. :)
