### ISSUE TITLE
ONVIF issues

### ISSUE THREAD

**Issue by TungstenE2** [roleoroleo/yi-hack-Allwinner-v2#863]
Using:  v0.3.2, h52ga, SFUS

- ONVIF WS-Discovery nort working, If I enable 'ONVIF WS-Discovery' in 'ONVIF configuration' I would expect that tools which scan my network for ONVIF devices would detect the cam, but this is not working, while working with other cams on my network. Tested with 'tinyCam Monitor' on Android and 'ONVIF Device Manager' on Windows.

- 'ONVIF audio decoder (backchannel)' is my assumption right that this is for the backchannel, so you can talk to the cam speaker? Seems not to be working

- 'ONVIF Network Interface' why is there Ethernet option for cams with only wireless available?

- please rename ONVIF Profiles according to official profile namings. See: https://www.onvif.org/profiles/
You name the profiles High and Low, but official Profiles are named A, C, D, G, M, S and T, So how do they match?

**Comment by roleoroleo** [comment]
> ONVIF WS-Discovery nort working, If I enable 'ONVIF WS-Discovery' in 'ONVIF configuration' I would expect that tools which scan my network for ONVIF devices would detect the cam, but this is not working, while working with other cams on my network. Tested with 'tinyCam Monitor' on Android and 'ONVIF Device Manager' on Windows.

Is the tool you are running in the same network? I'm currently using with ODM without problem.
Is the daemon running properly inside the cam?

> 'ONVIF audio decoder (backchannel)' is my assumption right that this is for the backchannel, so you can talk to the cam speaker? Seems not to be working

This feature is hard to test. You need a client able to create a backchannel (aac or xLaw). How are you testing it?
I tested it with ONVIF Device Test Tool 21.06.
I didn't test it with WebRTC because it doesn't work behind my traefik.

> 'ONVIF Network Interface' why is there Ethernet option for cams with only wireless available?

Simply I didn't create a function to detect which interfaces are available in the cam.
So I leaved this choice to the user.
And I don't know what happens when a user connects the cam with both interfaces. I haven't got cams with the ethernet.

> please rename ONVIF Profiles according to official profile namings. See: https://www.onvif.org/profiles/
You name the profiles High and Low, but official Profiles are named A, C, D, G, M, S and T, So how do they match?

There is a misunderstanding about the terms. When I write "ONVIF Profile" I mean the media profile: the content returned by "GetProfiles" function.
In our case there are two profiles: a high res profile and a low res profile.
The profile you mentioned is the set of feature supported by the cam and is fixed to "S" (although in the latest version there are some implementations related to the T profile).
